#!/usr/bin/env node
/**
 * build.mjs — two bundles from one source tree.
 *
 *   code.js        the plugin, as Figma loads it: one IIFE, no modules, no
 *                  imports, es2017 because the plugin sandbox is not a browser
 *                  with a modern baseline.
 *   dist/core.mjs  the pure core, as Node loads it, so `dry-run.mjs` can drive
 *                  exactly the code the plugin runs. There is no second
 *                  implementation of the mapping to keep in step.
 *
 * No runtime dependencies go into either: the core imports nothing but itself,
 * and `code.js` additionally uses Figma's own globals.
 *
 *   node build.mjs [--quiet] [--watch]
 */

import { mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import * as esbuild from 'esbuild';

const HERE = dirname(fileURLToPath(import.meta.url));
const quiet = process.argv.includes('--quiet');
const watch = process.argv.includes('--watch');

mkdirSync(join(HERE, 'dist'), { recursive: true });

const banner = {
  js: '/* Generated by machinery/figma-plugin/build.mjs — edit src/, never this file. */',
};

/** The plugin sandbox: one file, no module system, Figma globals available. */
const pluginConfig = {
  entryPoints: [join(HERE, 'src', 'code.ts')],
  outfile: join(HERE, 'code.js'),
  bundle: true,
  format: 'iife',
  target: 'es2017',
  platform: 'neutral',
  logLevel: quiet ? 'warning' : 'info',
  banner,
};

/** The core alone, for Node: the dry run drives the same functions the plugin does. */
const coreConfig = {
  entryPoints: [join(HERE, 'src', 'core', 'index.ts')],
  outfile: join(HERE, 'dist', 'core.mjs'),
  bundle: true,
  format: 'esm',
  target: 'node18',
  platform: 'neutral',
  logLevel: quiet ? 'warning' : 'info',
  banner,
};

if (watch) {
  const contexts = await Promise.all([esbuild.context(pluginConfig), esbuild.context(coreConfig)]);
  await Promise.all(contexts.map((context) => context.watch()));
  process.stdout.write('watching src/…\n');
} else {
  await Promise.all([esbuild.build(pluginConfig), esbuild.build(coreConfig)]);
  if (!quiet) process.stdout.write('built code.js and dist/core.mjs\n');
}
