/* Generated by machinery/figma-plugin/build.mjs — edit src/, never this file. */
"use strict";
(() => {
  var __defProp = Object.defineProperty;
  var __defProps = Object.defineProperties;
  var __getOwnPropDescs = Object.getOwnPropertyDescriptors;
  var __getOwnPropSymbols = Object.getOwnPropertySymbols;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __propIsEnum = Object.prototype.propertyIsEnumerable;
  var __defNormalProp = (obj, key2, value) => key2 in obj ? __defProp(obj, key2, { enumerable: true, configurable: true, writable: true, value }) : obj[key2] = value;
  var __spreadValues = (a, b) => {
    for (var prop in b || (b = {}))
      if (__hasOwnProp.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    if (__getOwnPropSymbols)
      for (var prop of __getOwnPropSymbols(b)) {
        if (__propIsEnum.call(b, prop))
          __defNormalProp(a, prop, b[prop]);
      }
    return a;
  };
  var __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));

  // src/core/apply.ts
  function applyPlan(plan, adapter) {
    const snapshot = adapter.readSnapshot();
    const collectionIds = /* @__PURE__ */ new Map();
    const modeIds = /* @__PURE__ */ new Map();
    const variableIds = /* @__PURE__ */ new Map();
    const collectionById = /* @__PURE__ */ new Map();
    for (const collection of snapshot.collections) {
      collectionIds.set(collection.name, collection.id);
      collectionById.set(collection.id, collection.name);
      for (const mode of collection.modes) modeIds.set(key(collection.name, mode.name), mode.id);
    }
    for (const variable of snapshot.variables) {
      const collectionName = collectionById.get(variable.collectionId);
      if (collectionName) variableIds.set(key(collectionName, variable.name), variable.id);
    }
    const failures = [];
    let applied = 0;
    const resolve = (value) => {
      if (value.kind === "ALIAS") {
        const id = variableIds.get(key(value.collection, value.name));
        if (!id) throw new Error(`alias target ${value.collection}/${value.name} does not exist`);
        return { kind: "ALIAS", id };
      }
      if (value.kind === "UNKNOWN") throw new Error(`cannot write an unreadable value: ${value.note}`);
      return value;
    };
    const structure = plan.actions.filter((a) => a.op !== "set-value");
    const values = plan.actions.filter((a) => a.op === "set-value");
    for (const action of structure) {
      try {
        switch (action.op) {
          case "create-collection": {
            const created = adapter.createCollection(action.collection);
            collectionIds.set(action.collection, created.id);
            adapter.renameMode(created.id, created.defaultModeId, action.firstMode);
            modeIds.set(key(action.collection, action.firstMode), created.defaultModeId);
            break;
          }
          case "rename-mode": {
            const collectionId = requireId(collectionIds, action.collection, "collection");
            const modeId = requireId(modeIds, key(action.collection, action.from), "mode");
            adapter.renameMode(collectionId, modeId, action.to);
            modeIds.delete(key(action.collection, action.from));
            modeIds.set(key(action.collection, action.to), modeId);
            break;
          }
          case "create-mode": {
            const collectionId = requireId(collectionIds, action.collection, "collection");
            const modeId = adapter.addMode(collectionId, action.mode);
            modeIds.set(key(action.collection, action.mode), modeId);
            break;
          }
          case "create-variable": {
            const collectionId = requireId(collectionIds, action.collection, "collection");
            const id = adapter.createVariable(collectionId, action.name, action.type);
            variableIds.set(key(action.collection, action.name), id);
            if (action.description) adapter.setDescription(id, action.description);
            break;
          }
          case "set-description": {
            const id = requireId(variableIds, key(action.collection, action.name), "variable");
            adapter.setDescription(id, action.to);
            break;
          }
          default:
            break;
        }
        applied += 1;
      } catch (error) {
        failures.push({ action, message: messageOf(error) });
      }
    }
    for (const action of values) {
      if (action.op !== "set-value") continue;
      try {
        const id = requireId(variableIds, key(action.collection, action.name), "variable");
        const modeId = requireId(modeIds, key(action.collection, action.mode), "mode");
        adapter.setValue(id, modeId, action.to, resolve);
        applied += 1;
      } catch (error) {
        failures.push({ action, message: messageOf(error) });
      }
    }
    return { applied, failures };
  }
  function key(collection, name) {
    return `${collection}\0${name}`;
  }
  function requireId(map, lookup, what) {
    const id = map.get(lookup);
    if (!id) throw new Error(`${what} "${lookup.split("\0").join("/")}" was expected to exist by now`);
    return id;
  }
  function messageOf(error) {
    return error instanceof Error ? error.message : String(error);
  }

  // src/core/token-model.ts
  var MODES_DIR = "modes";
  var MODES_MANIFEST = "modes.json";
  var ALIAS_PATTERN = /^\{([^{}]+)\}$/;
  var Diagnostics = class {
    constructor() {
      this.errors = [];
      this.warnings = [];
      this.seen = /* @__PURE__ */ new Set();
    }
    add(list, code, message, context) {
      const key2 = JSON.stringify([code, context.file || "", context.token || "", message]);
      if (this.seen.has(key2)) return;
      this.seen.add(key2);
      list.push(__spreadValues({ code, message }, context));
    }
    error(code, message, context = {}) {
      this.add(this.errors, code, message, context);
    }
    warn(code, message, context = {}) {
      this.add(this.warnings, code, message, context);
    }
    get ok() {
      return this.errors.length === 0;
    }
  };
  function isPlainObject(value) {
    return value !== null && typeof value === "object" && !Array.isArray(value);
  }
  function aliasTarget(value) {
    if (typeof value !== "string") return null;
    const match = ALIAS_PATTERN.exec(value.trim());
    return match ? match[1].trim() : null;
  }
  function flattenDocument(data, options) {
    const { file, layer, diagnostics, into } = options;
    if (!isPlainObject(data)) {
      diagnostics.error("invalid-document", "Token file must contain a JSON object at the top level.", { file });
      return;
    }
    const walk = (node, segments, inheritedType) => {
      const ownType = typeof node.$type === "string" ? node.$type : void 0;
      const path = segments.join(".");
      const childKeys = Object.keys(node).filter((key2) => key2.charAt(0) !== "$");
      const hasValue = Object.prototype.hasOwnProperty.call(node, "$value");
      if (hasValue) {
        if (childKeys.length > 0) {
          diagnostics.error(
            "token-has-children",
            `Token "${path}" carries $value and also has child keys (${childKeys.join(", ")}). A token cannot also be a group.`,
            { file, token: path }
          );
        }
        const existing = into.get(path);
        if (existing) {
          diagnostics.error(
            "duplicate-token",
            `Token "${path}" is declared in two files: ${existing.file} and ${file}.`,
            { file, token: path }
          );
          return;
        }
        into.set(path, {
          path,
          segments: segments.slice(),
          file,
          layer,
          rawValue: node.$value,
          ownType,
          inheritedType,
          type: ownType || inheritedType,
          description: typeof node.$description === "string" ? node.$description : void 0,
          deprecated: node.$deprecated
        });
        return;
      }
      if (childKeys.length === 0) {
        diagnostics.error(
          "missing-value",
          `"${path || "(root)"}" has no $value and no children. A token needs a $value; a group needs members.`,
          { file, token: path }
        );
        return;
      }
      for (const key2 of childKeys) {
        const child = node[key2];
        if (!isPlainObject(child)) {
          diagnostics.error(
            "invalid-node",
            `"${segments.concat(key2).join(".")}" is ${Array.isArray(child) ? "an array" : typeof child}. Every token and group must be an object.`,
            { file, token: segments.concat(key2).join(".") }
          );
          continue;
        }
        walk(child, segments.concat(key2), ownType || inheritedType);
      }
    };
    walk(data, [], void 0);
  }
  function discoverModes(bundleFiles, diagnostics) {
    const byId = /* @__PURE__ */ new Map();
    const modeFiles = Object.keys(bundleFiles).filter((name) => name.indexOf(`${MODES_DIR}/`) === 0 && name.slice(-5) === ".json").sort();
    for (const file of modeFiles) {
      const id = file.slice(MODES_DIR.length + 1, -".json".length);
      if (id.indexOf("/") !== -1) continue;
      byId.set(id, { id, file, overrides: /* @__PURE__ */ new Map() });
    }
    if (Object.prototype.hasOwnProperty.call(bundleFiles, MODES_MANIFEST)) {
      const manifest = bundleFiles[MODES_MANIFEST];
      const dimensions2 = [];
      if (isPlainObject(manifest) && Array.isArray(manifest.dimensions)) {
        for (const entry of manifest.dimensions) {
          if (!isPlainObject(entry) || typeof entry.name !== "string" || !Array.isArray(entry.modes)) {
            diagnostics.error(
              "invalid-modes-manifest",
              'Each entry of "dimensions" needs a string "name" and an array "modes".',
              { file: MODES_MANIFEST }
            );
            continue;
          }
          const members = [];
          for (const id of entry.modes) {
            if (typeof id !== "string" || !byId.has(id)) {
              diagnostics.error(
                "mode-file-missing",
                `Manifest dimension "${entry.name}" lists mode "${String(id)}" but ${MODES_DIR}/${String(id)}.json is not in the bundle.`,
                { file: MODES_MANIFEST }
              );
              continue;
            }
            byId.get(id).dimension = entry.name;
            members.push(id);
          }
          if (members.length > 0) dimensions2.push({ name: entry.name, modes: members });
        }
      } else {
        diagnostics.error("invalid-modes-manifest", 'Mode manifest must contain a "dimensions" array.', {
          file: MODES_MANIFEST
        });
      }
      for (const mode of byId.values()) {
        if (!mode.dimension) {
          diagnostics.error(
            "mode-not-in-manifest",
            `Mode file ${mode.file} is not listed in any dimension of ${MODES_MANIFEST}. Every mode file must belong to a dimension.`,
            { file: mode.file }
          );
        }
      }
      return { modes: byId, dimensions: dimensions2, source: MODES_MANIFEST };
    }
    const grouped = /* @__PURE__ */ new Map();
    for (const mode of byId.values()) {
      const dot = mode.id.indexOf(".");
      mode.dimension = dot > 0 ? mode.id.slice(0, dot) : "mode";
      const list = grouped.get(mode.dimension) || [];
      list.push(mode.id);
      grouped.set(mode.dimension, list);
    }
    const dimensions = Array.from(grouped.entries()).sort((a, b) => a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0).map(([name, modes]) => ({ name, modes: modes.sort() }));
    return { modes: byId, dimensions, source: "filenames" };
  }
  function loadBundle(bundle, diagnostics = new Diagnostics()) {
    const files = bundle && isPlainObject(bundle.files) ? bundle.files : {};
    const base = /* @__PURE__ */ new Map();
    const read = [];
    const modeInfo = discoverModes(files, diagnostics);
    const baseFiles = Object.keys(files).filter((name) => {
      if (name.slice(-5) !== ".json") return false;
      const slash = name.indexOf("/");
      if (slash === -1) return false;
      return name.slice(0, slash) !== MODES_DIR;
    }).sort();
    for (const file of baseFiles) {
      const layer = file.slice(0, file.indexOf("/"));
      read.push(file);
      flattenDocument(files[file], { file, layer, diagnostics, into: base });
    }
    for (const mode of modeInfo.modes.values()) {
      flattenDocument(files[mode.file], {
        file: mode.file,
        layer: MODES_DIR,
        diagnostics,
        into: mode.overrides
      });
      read.push(mode.file);
    }
    return {
      base,
      modes: modeInfo.modes,
      dimensions: modeInfo.dimensions,
      modeSource: modeInfo.source,
      files: read,
      diagnostics
    };
  }
  function effectiveType(path, nodes, seen = []) {
    if (seen.indexOf(path) !== -1) return void 0;
    const node = nodes.get(path);
    if (!node) return void 0;
    if (node.type) return node.type;
    const target = aliasTarget(node.rawValue);
    if (target === null) return void 0;
    return effectiveType(target, nodes, seen.concat(path));
  }
  function varyingDimensions(path, set) {
    const found = [];
    for (const dimension of set.dimensions) {
      for (const modeId of dimension.modes) {
        const mode = set.modes.get(modeId);
        if (mode && mode.overrides.has(path)) {
          found.push(dimension.name);
          break;
        }
      }
    }
    return found;
  }
  function nodeInMode(path, set, modeId) {
    const baseNode = set.base.get(path);
    if (!baseNode) return void 0;
    if (modeId === null) return baseNode;
    const mode = set.modes.get(modeId);
    const override = mode && mode.overrides.get(path);
    if (!override) return baseNode;
    return __spreadProps(__spreadValues({}, baseNode), {
      rawValue: override.rawValue,
      type: override.ownType || override.inheritedType || baseNode.type,
      file: override.file
    });
  }

  // src/core/map.ts
  var COMPOSITE_TYPES = /* @__PURE__ */ new Set([
    "shadow",
    "typography",
    "border",
    "transition",
    "gradient",
    "strokeStyle",
    "cubicBezier"
  ]);
  var TYPE_TABLE = {
    color: "COLOR",
    dimension: "FLOAT",
    number: "FLOAT",
    duration: "FLOAT",
    fontFamily: "STRING",
    string: "STRING",
    boolean: "BOOLEAN"
  };
  function figmaTypeFor(dtcgType, value) {
    if (dtcgType && COMPOSITE_TYPES.has(dtcgType)) return void 0;
    if (dtcgType && TYPE_TABLE[dtcgType]) return TYPE_TABLE[dtcgType];
    if (dtcgType === "fontWeight") return typeof value === "number" ? "FLOAT" : "STRING";
    if (dtcgType) return void 0;
    if (typeof value === "number") return "FLOAT";
    if (typeof value === "boolean") return "BOOLEAN";
    if (typeof value === "string") return "STRING";
    if (isColorObject(value)) return "COLOR";
    if (isDimensionObject(value)) return "FLOAT";
    return void 0;
  }
  function isColorObject(value) {
    return isPlainObject(value) && typeof value.colorSpace === "string" && Array.isArray(value.components);
  }
  function isDimensionObject(value) {
    return isPlainObject(value) && typeof value.value === "number" && typeof value.unit === "string";
  }
  function colorToRgba(value) {
    if (typeof value === "string") {
      return { ok: false, reason: `colour must be a DTCG object, not the string ${JSON.stringify(value)}` };
    }
    if (!isColorObject(value)) {
      return { ok: false, reason: "colour must be an object with colorSpace and components" };
    }
    if (value.colorSpace !== "srgb") {
      return {
        ok: false,
        reason: `colour space ${JSON.stringify(value.colorSpace)} has no Figma variable equivalent; only "srgb" is projected`
      };
    }
    const c = value.components;
    if (c.length !== 3 || !c.every((n) => typeof n === "number" && isFinite(n) && n >= 0 && n <= 1)) {
      return { ok: false, reason: `components must be three 0\u20131 floats; got ${JSON.stringify(c)}` };
    }
    const alpha = value.alpha === void 0 ? 1 : value.alpha;
    if (typeof alpha !== "number" || !isFinite(alpha) || alpha < 0 || alpha > 1) {
      return { ok: false, reason: `alpha must be a 0\u20131 float; got ${JSON.stringify(value.alpha)}` };
    }
    return { ok: true, value: { r: c[0], g: c[1], b: c[2], a: alpha } };
  }
  function mapValue(rawValue, declaredType) {
    const alias = aliasTarget(rawValue);
    if (alias !== null) {
      return { ok: true, alias, type: figmaTypeFor(declaredType, void 0) };
    }
    if (declaredType && COMPOSITE_TYPES.has(declaredType)) {
      return {
        ok: false,
        reason: `"${declaredType}" is a composite DTCG type and Figma variables hold single values. Figma models this as a style, not a variable.`
      };
    }
    const type = figmaTypeFor(declaredType, rawValue);
    if (!type) {
      if (Array.isArray(rawValue) || isPlainObject(rawValue)) {
        return {
          ok: false,
          reason: `no Figma variable type for a ${Array.isArray(rawValue) ? "list" : "structured"} value of $type ${JSON.stringify(declaredType)}`
        };
      }
      return { ok: false, reason: `no Figma variable type for $type ${JSON.stringify(declaredType)}` };
    }
    switch (type) {
      case "COLOR": {
        const parsed = colorToRgba(rawValue);
        if (!parsed.ok) return { ok: false, reason: parsed.reason };
        return { ok: true, type, value: { kind: "COLOR", value: parsed.value } };
      }
      case "FLOAT": {
        if (typeof rawValue === "number" && isFinite(rawValue)) {
          return { ok: true, type, value: { kind: "FLOAT", value: rawValue } };
        }
        if (isDimensionObject(rawValue)) {
          if (rawValue.unit === "px") {
            return { ok: true, type, value: { kind: "FLOAT", value: rawValue.value } };
          }
          if (declaredType === "duration" && (rawValue.unit === "ms" || rawValue.unit === "s")) {
            const ms = rawValue.unit === "s" ? rawValue.value * 1e3 : rawValue.value;
            return {
              ok: true,
              type,
              value: { kind: "FLOAT", value: ms },
              note: "duration projected in milliseconds"
            };
          }
          return {
            ok: false,
            reason: `dimension unit "${rawValue.unit}" cannot be projected: a Figma FLOAT is unitless, and converting would mean assuming a root size the token does not state`
          };
        }
        return { ok: false, reason: `expected a number or a DTCG dimension; got ${JSON.stringify(rawValue)}` };
      }
      case "STRING": {
        if (typeof rawValue === "string") {
          return { ok: true, type, value: { kind: "STRING", value: rawValue } };
        }
        if (Array.isArray(rawValue) && rawValue.length > 0 && rawValue.every((v) => typeof v === "string")) {
          const [first, ...rest] = rawValue;
          return {
            ok: true,
            type,
            value: { kind: "STRING", value: first },
            note: rest.length > 0 ? `narrowed to the first family; Figma holds one value, so the fallbacks (${rest.join(", ")}) are not represented` : void 0
          };
        }
        return { ok: false, reason: `expected a string or a list of strings; got ${JSON.stringify(rawValue)}` };
      }
      case "BOOLEAN": {
        if (typeof rawValue === "boolean") return { ok: true, type, value: { kind: "BOOLEAN", value: rawValue } };
        return { ok: false, reason: `expected a boolean; got ${JSON.stringify(rawValue)}` };
      }
      default:
        return { ok: false, reason: `unhandled Figma type ${type}` };
    }
  }
  function figmaName(tokenPath) {
    return tokenPath.split(".").join("/");
  }
  function valuesEqual(a, b) {
    if (!a || !b) return a === b;
    if (a.kind !== b.kind) return false;
    switch (a.kind) {
      case "COLOR": {
        const other = b.value;
        return near(a.value.r, other.r) && near(a.value.g, other.g) && near(a.value.b, other.b) && near(a.value.a, other.a);
      }
      case "FLOAT":
        return near(a.value, b.value);
      case "STRING":
      case "BOOLEAN":
        return a.value === b.value;
      case "ALIAS": {
        const other = b;
        return a.collection === other.collection && a.name === other.name;
      }
      case "UNKNOWN":
        return false;
      default:
        return false;
    }
  }
  function near(a, b) {
    return Math.abs(a - b) < 1e-6;
  }

  // src/core/plan.ts
  var SINGLE_MODE_NAME = "Default";
  function modeDisplayName(modeId, dimension) {
    const prefix = `${dimension}.`;
    return modeId.indexOf(prefix) === 0 ? modeId.slice(prefix.length) : modeId;
  }
  function planSync(bundle, snapshot) {
    const diagnostics = new Diagnostics();
    const set = loadBundle(bundle, diagnostics);
    const errors = diagnostics.errors.map((d) => ({
      code: d.code,
      message: d.message,
      token: d.token,
      file: d.file
    }));
    const warnings = diagnostics.warnings.map((d) => ({
      code: d.code,
      message: d.message,
      token: d.token,
      file: d.file
    }));
    const skipped = [];
    if (set.files.length === 0) {
      errors.push({
        code: "empty-bundle",
        message: "The bundle contains no token documents. Nothing to sync."
      });
    }
    const collectionOf = /* @__PURE__ */ new Map();
    const dimensionOf = /* @__PURE__ */ new Map();
    for (const [path, node] of set.base) {
      const varying = varyingDimensions(path, set);
      if (varying.length > 1) {
        errors.push({
          code: "cross-dimension-token",
          token: path,
          file: node.file,
          message: `"${path}" is overridden by ${varying.length} mode dimensions (${varying.join(", ")}). A Figma variable lives in one collection and holds one value per mode of that collection, so a token varying by two dimensions has no Figma representation. Express it the way the token layer already does: one slot token per mode of the last-applied dimension, set by the earlier dimension, and a selector token that aliases the slot.`
        });
        continue;
      }
      dimensionOf.set(path, varying.length === 1 ? varying[0] : null);
      collectionOf.set(path, varying.length === 1 ? varying[0] : node.layer);
    }
    const classified = /* @__PURE__ */ new Map();
    const classify = (path, seen) => {
      const cached = classified.get(path);
      if (cached) return cached;
      if (seen.indexOf(path) !== -1) {
        const result2 = {
          status: "error",
          problem: {
            code: "alias-cycle",
            token: path,
            message: `Alias cycle: ${seen.concat(path).join(" -> ")}`
          }
        };
        classified.set(path, result2);
        return result2;
      }
      const node = set.base.get(path);
      const target = aliasTarget(node.rawValue);
      let result;
      if (target !== null) {
        if (!set.base.has(target)) {
          result = {
            status: "error",
            problem: {
              code: "alias-not-found",
              token: path,
              file: node.file,
              message: `"${path}" references "{${target}}", which is not a token.`
            }
          };
        } else {
          const upstream = classify(target, seen.concat(path));
          result = upstream.status === "ok" ? upstream : upstream.status === "skip" ? { status: "skip", reason: `aliases "${target}", which is not projected: ${upstream.reason}` } : upstream;
        }
      } else {
        const declared = effectiveType(path, set.base);
        const mapped = mapValue(node.rawValue, declared);
        if (!mapped.ok) {
          result = { status: "skip", reason: mapped.reason };
        } else if ("alias" in mapped) {
          result = { status: "skip", reason: "unexpected alias" };
        } else {
          result = { status: "ok", type: mapped.type };
        }
      }
      classified.set(path, result);
      return result;
    };
    for (const path of set.base.keys()) {
      if (!collectionOf.has(path)) continue;
      const result = classify(path, []);
      if (result.status === "skip") {
        skipped.push({ token: path, type: effectiveType(path, set.base), reason: result.reason });
      } else if (result.status === "error") {
        errors.push(result.problem);
      }
    }
    const desiredCollections = /* @__PURE__ */ new Map();
    const collectionFor = (name) => {
      let collection = desiredCollections.get(name);
      if (collection) return collection;
      const dimension = set.dimensions.filter((d) => d.name === name)[0];
      if (dimension) {
        const modes = [];
        const modeIds = {};
        for (const modeId of dimension.modes) {
          const display = modeDisplayName(modeId, dimension.name);
          if (Object.prototype.hasOwnProperty.call(modeIds, display)) {
            errors.push({
              code: "mode-name-collision",
              collection: name,
              message: `Dimension "${name}" has two modes that both shorten to "${display}". Mode names inside a collection must be distinct.`
            });
            continue;
          }
          modes.push(display);
          modeIds[display] = modeId;
        }
        collection = { name, origin: "dimension", modes, modeIds };
      } else {
        collection = {
          name,
          origin: "layer",
          modes: [SINGLE_MODE_NAME],
          modeIds: { [SINGLE_MODE_NAME]: null }
        };
      }
      desiredCollections.set(name, collection);
      return collection;
    };
    const desired = [];
    for (const [path, node] of set.base) {
      const classification = classified.get(path);
      if (!classification || classification.status !== "ok") continue;
      const collectionName = collectionOf.get(path);
      const collection = collectionFor(collectionName);
      const name = figmaName(path);
      if (name.indexOf(":") !== -1 || name.charAt(0) === "/" || name.indexOf("//") !== -1) {
        errors.push({
          code: "unusable-variable-name",
          token: path,
          message: `"${path}" becomes the Figma name "${name}", which Figma will not accept.`
        });
        continue;
      }
      const values = {};
      let usable = true;
      for (const modeName of collection.modes) {
        const modeId = collection.modeIds[modeName];
        const inMode = nodeInMode(path, set, modeId);
        const target = aliasTarget(inMode.rawValue);
        if (target !== null) {
          const targetClass = classified.get(target);
          if (!set.base.has(target)) {
            errors.push({
              code: "alias-not-found",
              token: path,
              file: inMode.file,
              message: `"${path}" references "{${target}}" in mode "${modeName}", which is not a token.`
            });
            usable = false;
            break;
          }
          if (!targetClass || targetClass.status !== "ok") {
            skipped.push({
              token: path,
              type: effectiveType(path, set.base),
              reason: `in mode "${modeName}" it aliases "${target}", which is not projected`
            });
            usable = false;
            break;
          }
          if (targetClass.type !== classification.type) {
            errors.push({
              code: "alias-type-mismatch",
              token: path,
              file: inMode.file,
              message: `"${path}" is a ${classification.type} variable but in mode "${modeName}" it aliases "${target}", which is ${targetClass.type}. Figma requires an alias to match the variable's resolved type.`
            });
            usable = false;
            break;
          }
          if (!collectionOf.has(target)) {
            usable = false;
            break;
          }
          values[modeName] = {
            kind: "ALIAS",
            collection: collectionOf.get(target),
            name: figmaName(target)
          };
          continue;
        }
        const mapped = mapValue(inMode.rawValue, inMode.type || effectiveType(path, set.base));
        if (!mapped.ok) {
          skipped.push({ token: path, type: inMode.type, reason: `in mode "${modeName}": ${mapped.reason}` });
          usable = false;
          break;
        }
        if ("alias" in mapped) {
          usable = false;
          break;
        }
        if (mapped.type !== classification.type) {
          errors.push({
            code: "type-varies-by-mode",
            token: path,
            file: inMode.file,
            message: `"${path}" is ${classification.type} in the base layer but ${mapped.type} in mode "${modeName}". A Figma variable has one resolved type across every mode.`
          });
          usable = false;
          break;
        }
        if (mapped.note) {
          warnings.push({ code: "value-narrowed", token: path, message: `${path} (${modeName}): ${mapped.note}` });
        }
        values[modeName] = mapped.value;
      }
      if (!usable) continue;
      desired.push({
        token: path,
        name,
        collection: collectionName,
        type: classification.type,
        description: describeToken(node),
        values
      });
    }
    const actions = [];
    const orphans = [];
    const existingCollections = /* @__PURE__ */ new Map();
    for (const collection of snapshot.collections) existingCollections.set(collection.name, collection);
    const variablesByCollection = /* @__PURE__ */ new Map();
    for (const variable of snapshot.variables) {
      const list = variablesByCollection.get(variable.collectionId) || [];
      list.push(variable);
      variablesByCollection.set(variable.collectionId, list);
    }
    const desiredByCollection = /* @__PURE__ */ new Map();
    for (const variable of desired) {
      const list = desiredByCollection.get(variable.collection) || [];
      list.push(variable);
      desiredByCollection.set(variable.collection, list);
    }
    const collectionSummaries = [];
    const orderedCollections = orderCollections(desiredCollections, set);
    for (const collection of orderedCollections) {
      const existing = existingCollections.get(collection.name);
      const members = desiredByCollection.get(collection.name) || [];
      collectionSummaries.push({
        name: collection.name,
        origin: collection.origin,
        modes: collection.modes,
        variableCount: members.length,
        exists: Boolean(existing)
      });
      const existingModeNames = existing ? existing.modes.map((m) => m.name) : [];
      if (!existing) {
        actions.push({ op: "create-collection", collection: collection.name, firstMode: collection.modes[0] });
        for (const mode of collection.modes.slice(1)) {
          actions.push({ op: "create-mode", collection: collection.name, mode });
        }
      } else {
        const existingMembers = variablesByCollection.get(existing.id) || [];
        const placeholderOnly = existing.modes.length === 1 && existingMembers.length === 0 && existingModeNames.indexOf(collection.modes[0]) === -1;
        if (placeholderOnly) {
          actions.push({
            op: "rename-mode",
            collection: collection.name,
            from: existing.modes[0].name,
            to: collection.modes[0]
          });
          existingModeNames[0] = collection.modes[0];
        }
        for (const mode of collection.modes) {
          if (existingModeNames.indexOf(mode) === -1) {
            actions.push({ op: "create-mode", collection: collection.name, mode });
          }
        }
        for (const mode of existingModeNames) {
          if (collection.modes.indexOf(mode) === -1) {
            orphans.push({
              kind: "mode",
              collection: collection.name,
              name: mode,
              note: "no dimension in the token root declares this mode"
            });
          }
        }
      }
      const existingByName = /* @__PURE__ */ new Map();
      if (existing) {
        for (const variable of variablesByCollection.get(existing.id) || []) {
          existingByName.set(variable.name, variable);
        }
      }
      const modeIdByName = /* @__PURE__ */ new Map();
      if (existing) for (const mode of existing.modes) modeIdByName.set(mode.name, mode.id);
      for (const variable of members) {
        const current = existingByName.get(variable.name);
        if (!current) {
          actions.push({
            op: "create-variable",
            collection: collection.name,
            name: variable.name,
            token: variable.token,
            type: variable.type,
            description: variable.description
          });
        } else if (current.resolvedType !== variable.type) {
          errors.push({
            code: "type-conflict",
            token: variable.token,
            collection: collection.name,
            message: `"${variable.name}" already exists in collection "${collection.name}" as ${current.resolvedType}, but the token is ${variable.type}. A variable's resolved type cannot be changed, and this plugin does not delete. Remove the variable in Figma, or rename the token.`
          });
          continue;
        } else if (current.description !== variable.description) {
          actions.push({
            op: "set-description",
            collection: collection.name,
            name: variable.name,
            token: variable.token,
            from: current.description,
            to: variable.description
          });
        }
        for (const modeName of collection.modes) {
          const next = variable.values[modeName];
          if (!next) continue;
          const modeId = modeIdByName.get(modeName);
          const currentValue = current && modeId ? current.valuesByMode[modeId] : void 0;
          if (valuesEqual(currentValue, next)) continue;
          actions.push({
            op: "set-value",
            collection: collection.name,
            name: variable.name,
            token: variable.token,
            mode: modeName,
            from: currentValue === void 0 ? null : currentValue,
            to: next
          });
        }
      }
      if (existing) {
        const desiredNames = new Set(members.map((v) => v.name));
        for (const variable of variablesByCollection.get(existing.id) || []) {
          if (desiredNames.has(variable.name)) continue;
          const movedTo = desired.filter((v) => v.name === variable.name)[0];
          orphans.push({
            kind: "variable",
            collection: collection.name,
            name: variable.name,
            note: movedTo ? `the token now varies by "${movedTo.collection}" and has moved to that collection; this copy is left for you to delete` : "no token in the source declares it"
          });
        }
      }
    }
    const managed = new Set(orderedCollections.map((c) => c.name));
    const untouched = snapshot.collections.filter((c) => !managed.has(c.name)).map((c) => c.name);
    const creates = actions.filter(
      (a) => a.op === "create-collection" || a.op === "create-mode" || a.op === "create-variable"
    ).length;
    return {
      collections: collectionSummaries,
      actions,
      errors,
      warnings,
      skipped,
      orphans,
      untouched,
      signature: signatureOf(actions),
      stats: {
        tokensRead: set.base.size,
        variablesPlanned: desired.length,
        creates,
        updates: actions.length - creates
      }
    };
  }
  function orderCollections(collections, set) {
    const layers = Array.from(collections.values()).filter((c) => c.origin === "layer").sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0);
    const dimensions = [];
    for (const dimension of set.dimensions) {
      const found = collections.get(dimension.name);
      if (found) dimensions.push(found);
    }
    return layers.concat(dimensions);
  }
  function describeToken(node) {
    const parts = [];
    if (node.deprecated) {
      parts.push(typeof node.deprecated === "string" ? `[deprecated: ${node.deprecated}]` : "[deprecated]");
    }
    if (node.description) parts.push(node.description);
    return parts.join(" ");
  }
  function signatureOf(actions) {
    const text = JSON.stringify(actions);
    let hash = 2166136261;
    for (let i = 0; i < text.length; i += 1) {
      hash ^= text.charCodeAt(i);
      hash = Math.imul(hash, 16777619) >>> 0;
    }
    return `${(hash >>> 0).toString(16).padStart(8, "0")}-${actions.length}`;
  }
  function isApplicable(plan) {
    return plan.errors.length === 0;
  }

  // src/figma-adapter.ts
  async function captureSnapshot() {
    const collections = await figma.variables.getLocalVariableCollectionsAsync();
    const variables = await figma.variables.getLocalVariablesAsync();
    const nameById = /* @__PURE__ */ new Map();
    for (const variable of variables) {
      nameById.set(variable.id, { name: variable.name, collectionId: variable.variableCollectionId });
    }
    const collectionNameById = /* @__PURE__ */ new Map();
    for (const collection of collections) collectionNameById.set(collection.id, collection.name);
    const snapshotVariables = variables.map((variable) => {
      const valuesByMode = {};
      for (const modeId of Object.keys(variable.valuesByMode)) {
        valuesByMode[modeId] = fromFigmaValue(variable.valuesByMode[modeId], nameById, collectionNameById);
      }
      return {
        id: variable.id,
        name: variable.name,
        collectionId: variable.variableCollectionId,
        resolvedType: variable.resolvedType,
        description: variable.description || "",
        valuesByMode
      };
    });
    return {
      collections: collections.map((collection) => ({
        id: collection.id,
        name: collection.name,
        defaultModeId: collection.defaultModeId,
        modes: collection.modes.map((mode) => ({ id: mode.modeId, name: mode.name }))
      })),
      variables: snapshotVariables
    };
  }
  function fromFigmaValue(value, nameById, collectionNameById) {
    if (typeof value === "number") return { kind: "FLOAT", value };
    if (typeof value === "string") return { kind: "STRING", value };
    if (typeof value === "boolean") return { kind: "BOOLEAN", value };
    if (value && typeof value === "object") {
      const asAlias = value;
      if (asAlias.type === "VARIABLE_ALIAS") {
        const target = nameById.get(asAlias.id);
        const collection = target ? collectionNameById.get(target.collectionId) : void 0;
        if (target && collection) return { kind: "ALIAS", collection, name: target.name };
        return { kind: "UNKNOWN", note: "alias to a variable outside this file" };
      }
      const rgba = value;
      if (typeof rgba.r === "number") {
        return { kind: "COLOR", value: { r: rgba.r, g: rgba.g, b: rgba.b, a: typeof rgba.a === "number" ? rgba.a : 1 } };
      }
    }
    return { kind: "UNKNOWN", note: "value shape this plugin does not read" };
  }
  var FigmaVariables = class _FigmaVariables {
    constructor(snapshot, collections, variables) {
      this.snapshot = snapshot;
      this.collections = /* @__PURE__ */ new Map();
      this.variables = /* @__PURE__ */ new Map();
      for (const collection of collections) this.collections.set(collection.id, collection);
      for (const variable of variables) this.variables.set(variable.id, variable);
    }
    static async create() {
      const snapshot = await captureSnapshot();
      const collections = await figma.variables.getLocalVariableCollectionsAsync();
      const variables = await figma.variables.getLocalVariablesAsync();
      return new _FigmaVariables(snapshot, collections, variables);
    }
    readSnapshot() {
      return this.snapshot;
    }
    createCollection(name) {
      const collection = figma.variables.createVariableCollection(name);
      this.collections.set(collection.id, collection);
      return {
        id: collection.id,
        defaultModeId: collection.defaultModeId,
        defaultModeName: collection.modes[0].name
      };
    }
    renameMode(collectionId, modeId, name) {
      this.collection(collectionId).renameMode(modeId, name);
    }
    addMode(collectionId, name) {
      return this.collection(collectionId).addMode(name);
    }
    createVariable(collectionId, name, type) {
      const variable = figma.variables.createVariable(name, this.collection(collectionId), type);
      this.variables.set(variable.id, variable);
      return variable.id;
    }
    setDescription(variableId, description) {
      this.variable(variableId).description = description;
    }
    setValue(variableId, modeId, value, resolve) {
      const variable = this.variable(variableId);
      const resolved = resolve(value);
      if (resolved.kind === "ALIAS") {
        variable.setValueForMode(modeId, figma.variables.createVariableAlias(this.variable(resolved.id)));
        return;
      }
      variable.setValueForMode(modeId, resolved.value);
    }
    collection(id) {
      const found = this.collections.get(id);
      if (!found) throw new Error(`collection ${id} is not loaded`);
      return found;
    }
    variable(id) {
      const found = this.variables.get(id);
      if (!found) throw new Error(`variable ${id} is not loaded`);
      return found;
    }
  };

  // src/code.ts
  var pending = null;
  figma.showUI(__html__, { width: 720, height: 640, themeColors: true });
  figma.ui.onmessage = async (message) => {
    try {
      if (message.type === "close") {
        figma.closePlugin();
        return;
      }
      if (message.type === "preview") {
        const snapshot = await captureSnapshot();
        const plan = planSync(message.bundle, snapshot);
        pending = { bundle: message.bundle, plan };
        figma.ui.postMessage({ type: "plan", plan });
        return;
      }
      if (message.type === "apply") {
        if (!pending) {
          figma.ui.postMessage({ type: "error", message: "Nothing to apply. Preview the changes first." });
          return;
        }
        if (!isApplicable(pending.plan)) {
          figma.ui.postMessage({
            type: "error",
            message: "This plan has errors. Fix the token source and preview again \u2014 a partial projection is drift."
          });
          return;
        }
        const adapter = await FigmaVariables.create();
        const fresh = planSync(pending.bundle, adapter.readSnapshot());
        if (fresh.signature !== message.signature) {
          pending = { bundle: pending.bundle, plan: fresh };
          figma.ui.postMessage({
            type: "stale",
            message: "The document changed since the preview. Here is the current diff \u2014 review it and confirm again.",
            plan: fresh
          });
          return;
        }
        const result = applyPlan(fresh, adapter);
        const after = planSync(pending.bundle, await captureSnapshot());
        pending = { bundle: pending.bundle, plan: after };
        figma.ui.postMessage({
          type: "applied",
          applied: result.applied,
          failures: result.failures.map((f) => ({ message: f.message, action: f.action })),
          remaining: after.actions.length,
          plan: after
        });
        figma.notify(
          result.failures.length === 0 ? `Sync complete \u2014 ${result.applied} change${result.applied === 1 ? "" : "s"} written.` : `Sync finished with ${result.failures.length} failure${result.failures.length === 1 ? "" : "s"}.`
        );
        return;
      }
    } catch (error) {
      figma.ui.postMessage({
        type: "error",
        message: error instanceof Error ? `${error.message}` : String(error)
      });
    }
  };
})();
